@echo off
title NEWVIRUS
color 3
color 3C

echo HACKED LOL
timeout /t 2 /nobreak >nul

start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles
start "" https://youtu.be/LYl5JpILles

:spam
echo HACKED LOL
goto spam